"""pdf_utils.py — Generate PDF reports from research content.

Uses fpdf2 (pure Python, no system dependencies).
Converts markdown-formatted research reports to clean PDF files.
"""
import os
import re
import uuid
import datetime

STATIC_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "static_media")
os.makedirs(STATIC_DIR, exist_ok=True)


def _strip_markdown(text: str) -> str:
    """Convert basic markdown to plain text for PDF."""
    text = re.sub(r'#{1,6}\s*', '', text)          # headings
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)   # bold
    text = re.sub(r'\*(.*?)\*', r'\1', text)        # italic
    text = re.sub(r'`(.*?)`', r'\1', text)          # inline code
    text = re.sub(r'\[(.*?)\]\(.*?\)', r'\1', text) # links
    text = re.sub(r'^\s*[-*+]\s+', '• ', text, flags=re.MULTILINE)  # bullets
    return text.strip()


def generate_research_pdf(title: str, content: str, sources: list = None) -> str:
    """
    Generate a PDF from research content.
    Returns the URL path to the generated PDF file.
    """
    try:
        from fpdf import FPDF, XPos, YPos

        class XynthPDF(FPDF):
            def header(self):
                self.set_fill_color(15, 15, 25)
                self.rect(0, 0, 210, 20, 'F')
                self.set_font('Helvetica', 'B', 11)
                self.set_text_color(124, 92, 252)
                self.cell(0, 10, 'Xynth Research', align='L', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                self.set_text_color(200, 200, 210)

            def footer(self):
                self.set_y(-12)
                self.set_font('Helvetica', '', 8)
                self.set_text_color(120, 120, 140)
                date_str = datetime.date.today().strftime('%B %d, %Y')
                self.cell(0, 10, f'Generated by Xynth Research · {date_str} · Page {self.page_no()}', align='C')

        pdf = XynthPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        pdf.set_margins(18, 25, 18)

        # Title
        pdf.set_font('Helvetica', 'B', 18)
        pdf.set_text_color(240, 240, 250)
        safe_title = title.encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 10, safe_title, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(4)

        # Date line
        pdf.set_font('Helvetica', '', 10)
        pdf.set_text_color(130, 130, 160)
        date_str = datetime.date.today().strftime('%B %d, %Y')
        pdf.cell(0, 6, f'Research Report · {date_str}', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(6)

        # Divider
        pdf.set_draw_color(60, 60, 90)
        pdf.set_line_width(0.5)
        pdf.line(18, pdf.get_y(), 192, pdf.get_y())
        pdf.ln(8)

        # Content — parse sections
        pdf.set_text_color(220, 220, 235)
        lines = content.split('\n')

        for line in lines:
            stripped = line.strip()
            if not stripped:
                pdf.ln(3)
                continue

            if stripped.startswith('## ') or stripped.startswith('# '):
                # Section heading
                heading = re.sub(r'^#{1,3}\s*', '', stripped)
                heading = heading.encode('latin-1', 'replace').decode('latin-1')
                pdf.ln(4)
                pdf.set_font('Helvetica', 'B', 13)
                pdf.set_text_color(124, 92, 252)
                pdf.multi_cell(0, 8, heading, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.set_text_color(220, 220, 235)
                pdf.ln(2)

            elif stripped.startswith('- ') or stripped.startswith('• '):
                # Bullet
                bullet_text = re.sub(r'^[-•]\s*', '', stripped)
                bullet_text = _strip_markdown(bullet_text)
                bullet_text = bullet_text.encode('latin-1', 'replace').decode('latin-1')
                pdf.set_font('Helvetica', '', 10)
                pdf.cell(6, 6, '•', new_x=XPos.RIGHT, new_y=YPos.TOP)
                pdf.multi_cell(0, 6, bullet_text, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

            elif re.match(r'^\[\d+\]', stripped):
                # Reference
                ref = _strip_markdown(stripped)
                ref = ref.encode('latin-1', 'replace').decode('latin-1')
                pdf.set_font('Helvetica', '', 9)
                pdf.set_text_color(150, 150, 180)
                pdf.multi_cell(0, 5, ref, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.set_text_color(220, 220, 235)

            else:
                # Normal paragraph text
                plain = _strip_markdown(stripped)
                plain = plain.encode('latin-1', 'replace').decode('latin-1')
                pdf.set_font('Helvetica', '', 10)
                pdf.multi_cell(0, 6, plain, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Save
        filename = f"research_{uuid.uuid4().hex[:10]}.pdf"
        filepath = os.path.join(STATIC_DIR, filename)
        pdf.output(filepath)
        return f"/static_media/{filename}"

    except ImportError:
        return _generate_pdf_fallback(title, content)
    except Exception as e:
        print(f"PDF generation error: {e}")
        return ""


def _generate_pdf_fallback(title: str, content: str) -> str:
    """Fallback: save as plain text file if fpdf2 not available."""
    filename = f"research_{uuid.uuid4().hex[:10]}.txt"
    filepath = os.path.join(STATIC_DIR, filename)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(f"{title}\n{'=' * len(title)}\n\n{content}")
    return f"/static_media/{filename}"
